[[pages]]
path = "main.py"
name = "Home"
icon = ":house:"

[[pages]]
name = "Topic Modelling"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "pages/topic_modelling.py"
name = "Example Four"
icon = "ğŸ“–"

[[pages]]
name = "Topic Trajectory"
icon = ":horse:"
is_section = true

[[pages]]
path = "pages/topic_trajectory.py"

[[pages]]
name = "Simulations"
icon = ":horse:"
is_section = true

[[pages]]
path = "pages/simulations.py"